# You Podfile should look similar to this file. React Native currently does not support use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'example' do
  rn_path = '../node_modules/react-native'
  rn_yandex_mapkit_path = '../../'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'DevSupport',
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    # 'BatchedBridge', # REMOVE COMMENT if you use RN <0.54
  ]

  pod 'react-native-yandex-map-kit', path: rn_yandex_mapkit_path
end